name: MongoDB CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mongodb-ci:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0  # Use the required MongoDB version
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongo --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9" # Adjust based on your requirements

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Wait for MongoDB to be ready
      run: |
        for i in {1..10}; do
          if nc -z localhost 27017; then
            echo "MongoDB is ready"; exit 0
          fi
          echo "Waiting for MongoDB..."; sleep 3
        done
        echo "MongoDB did not become ready in time"; exit 1

    
        
    - name: Show MongoDB Collections
      run: |
          echo "Listing collections in the 'my_database' database"
          docker exec $(docker ps -q --filter "ancestor=mongo:5.0") mongo my_database --eval "printjson(db.getCollectionNames())"
      